FROM nginx:stable

COPY proxy_params /etc/nginx/proxy_params
COPY production.nginx.conf /etc/nginx/conf.d/aia.conf

RUN mkdir -p /var/www/healthcheck
RUN echo '{"status": "ok"}' > /var/www/healthcheck/index.html

CMD /usr/sbin/nginx -c /etc/nginx/nginx.conf -g 'daemon off;'
